# Login with user email & password
# POST http://localhost:5000/login
# Content-Type: application/json
# Authorization: Bearer 123
# Client-Key: xxx

# {
#     "email":"sushant87@gmail.com",
#     "password":"Asdef@123"
# }

# Logout user
# POST http://localhost:5000/logout
# Content-Type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc5MzU1NTAsIm5iZiI6MTU5NzkzNTU1MCwianRpIjoiZDhiZTM2ZDYtZjk3Ni00NDNhLWEwYzAtOWI4YTQ5ZjZiYTEzIiwiZXhwIjoxNTk3OTM2NDUwLCJpZGVudGl0eSI6eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4ifSwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJ1c2VyX3JvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjF9fQ.3igHStaBm3zgAKrpAsoqw5RpuqBsb6J1Byl8ldKBR4A

# Get user with id 1
# GET http://localhost:5000/user/1
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc5MzU1NTAsIm5iZiI6MTU5NzkzNTU1MCwianRpIjoiZDhiZTM2ZDYtZjk3Ni00NDNhLWEwYzAtOWI4YTQ5ZjZiYTEzIiwiZXhwIjoxNTk3OTM2NDUwLCJpZGVudGl0eSI6eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4ifSwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJ1c2VyX3JvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjF9fQ.3igHStaBm3zgAKrpAsoqw5RpuqBsb6J1Byl8ldKBR4A

# Update user password
# PUT http://localhost:5000/user/3
# Content-Type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc5MzU1NTAsIm5iZiI6MTU5NzkzNTU1MCwianRpIjoiZDhiZTM2ZDYtZjk3Ni00NDNhLWEwYzAtOWI4YTQ5ZjZiYTEzIiwiZXhwIjoxNTk3OTM2NDUwLCJpZGVudGl0eSI6eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4ifSwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJ1c2VyX3JvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjF9fQ.3igHStaBm3zgAKrpAsoqw5RpuqBsb6J1Byl8ldKBR4A

# {
#     "email":"sushant87@gmail.com",
#     "password":"Asdef@123",
#     "new_password":"Welcome@123"
# }

# Update user with empty fields
# PUT http://localhost:5000/user/3
# Content-Type: application/json
# Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc5MzU1NTAsIm5iZiI6MTU5NzkzNTU1MCwianRpIjoiZDhiZTM2ZDYtZjk3Ni00NDNhLWEwYzAtOWI4YTQ5ZjZiYTEzIiwiZXhwIjoxNTk3OTM2NDUwLCJpZGVudGl0eSI6eyJ1c2VyX2lkIjoxLCJyb2xlIjoiYWRtaW4ifSwiZnJlc2giOnRydWUsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2NsYWltcyI6eyJ1c2VyX3JvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjF9fQ.3igHStaBm3zgAKrpAsoqw5RpuqBsb6J1Byl8ldKBR4A

# {
#     "email":"sushant87@gmail.com"
# }